TrajectoryPlannerROS:
  max_vel_x: 2.0
  min_vel_x: 0.1
  max_vel_theta: 10.0
  min_in_place_vel_theta: 1.0

  acc_lim_theta: 10.0
  acc_lim_x: 5.0
  acc_lim_y: 5.0

  #The velocity the robot will command when trying to escape from a stuck situation
  escape_vel: -0.5

  occdist_scale: 0.5
  heading_lookahead: 0.6
  dwa: true
  publish_cost_grid_pc: true

  sim_time: 1.0

  holonomic_robot: false

  xy_goal_tolerance: 1.0
