obstacle_range: 5.0
raytrace_range: 5.0
footprint: [[0.35, 0.25], [0.35, -0.25], [-0.35, -0.25], [-0.35, 0.25]]
#robot_radius: ir_of_robot
inflation_radius: 0.5
cost_scaling_factor: 1.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: link_hokuyo, data_type: LaserScan, topic: Giskard/laser/scan, marking: true, clearing: true}
