Giskard:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint_camera_controller:
    type: effort_controllers/JointPositionController
    joint: joint_camera
    pid: {p: 100.0, i: 10.0, d: 15.0}
  joint_camera_vertical_controller:
    type: effort_controllers/JointPositionController
    joint: joint_camera_vertical
    pid: {p: 100.0, i: 10.0, d: 10.0}
